### ISSUE TITLE
dotnet core compatibility

### ISSUE THREAD

**Issue by nicowitteman** [melanchall/drywetmidi#1]
Hi!
Any plans for making this library dotnet core-compatible?
Kind regards,
Nico Witteman

**Comment by melanchall** [comment]
Hi Nico,

Currently I'm not planning to port the library to .NET Core. At now there are not so much users of the DryWetMIDI to proceed with .NET Core compatibility. This task can take some time but currently I'm focusing on new features of the library. But maybe in the future I'll come back to your issue :)

Anyway thank you for your interest to the DryWetMIDI! Feel free to open new issues and ask any questions about the library.

Max

**Comment by nicowitteman** [comment]
Hi Max,
I switched to framework, and I think the library is very useful. Now I have this issue:
In a MIDI file [bwv227.zip](https://github.com/melanchall/drywetmidi/files/1185023/bwv227.zip)
there is a track named "Ténor". In SequenceTrackNameEvent.Text it is represented as "T?nor". That is a pity, because I want to write the tracks away as files with their trackname. This one fails. Any suggestions?
Nico

**Comment by melanchall** [comment]
Hi Nico,

It is because the `Text` of any text-based meta event is processed in ASCII encoding. Obviously the `é` symbol doesn't belong this encoding. I'm planning to add other encodings support later. Maybe as a first iteration I will introduce kind of `TextEncoding` property in `ReadingSettings`/`WritingSettings` so you will be able to specify desired encoding for strings serialization/deserialization. Yes, sounds like a plan.

Thank you for your feedback and for remebering me about non-ASCII encodings in text-based meta events. I'll try to provide a solution in the next release which should be at the beginning of August.

Max

**Comment by nicowitteman** [comment]
Thanks Max, I will await the update.
Nico

**Comment by melanchall** [comment]
Nico, I've created separate issue for the non-ASCII encodings support (#2) and moved all our discussion about this problem to the first post of the new issue. All comments on this bug should be placed there.

This issue for discussion about .NET Core support only. One problem – one issue. Otherwise it will be difficult for me to maintain list of issues and link commits to specific ones :)

Max

**Comment by melanchall** [comment]
@nicowitteman,

DryWetMIDI 1.2.0 has been released. This release contains a fix for the #2.

**Comment by nicowitteman** [comment]
I see I never replied, sorry about that. Thanks Max and a happy new year.
