### ISSUE TITLE
Feature request: create virtual midi ports

### ISSUE THREAD

**Issue by MusicalMiqo** [melanchall/drywetmidi#117]
It would be great if drywetmidi can create virtual midi ports which other applications can listen/send data to. Just like the way loopMIDI functions, except we'll be able to do it in-library. Would this be easy/practical to implement? Thank you so much!

**Comment by melanchall** [comment]
Hi,

Unfortunately it's not possible to implement this feature in the near future. loopMIDI and other loopback MIDI software works due to custom Windows driver which force Windows think that there is a MIDI device in the system. So even if DryWetMIDI will provide this feature, you'll need to install a driver, so there is no any difference with mentioned software.

Also I'd like to note that the difficulty is related with Windows only. On macOS and Linux there is built-in API to create virtual ports. But Devices API of DWM is Windows only at now.

Please don't close the issue. Maybe I'll return to it later.

Thanks for the feature request!

**Comment by melanchall** [comment]
Well, virtual devices will be supported in the next release for macOS. For Windows it still need to have kernel-mode driver to have virtual devices. Maybe I'll provide support via 3d party product.

**Comment by melanchall** [comment]
I've implemented virtual devices creation on macOS and it will be available in the next release.

As for Windows, I've decided to not provide support via 3d party products because of licensing problems which can occur either for me or users of the library. So on Windows you need to deal with virtual devices by yourself. I recommend to try [virtualMIDI SDK](https://www.tobias-erichsen.de/software/virtualmidi/virtualmidi-sdk.html) which you can use from C# code (I've checked, it works).

**Comment by UlyssesWu** [comment]
Although the virtualMIDI SDK works, the license is a big problem for developers. Still waiting for an open-source or literally-free replacement for that.
