### ISSUE TITLE
player.Finished

### ISSUE THREAD

**Issue by wolfy01** [melanchall/drywetmidi#130]
For some reason:
```csharp
playback.Finished += playerFinished;
```
Isn't working for me. playerFinished code: 
```csharp
        private void playerFinished(object sender, EventArgs e) {
            Console.WriteLine("Playback finished.");
        }
```

**Comment by melanchall** [comment]
Please provide full code how you create and start a playback.

**Comment by wolfy01** [comment]
> Please provide full code how you create and start a playback.
```csharp
                playerThread = new Thread(
                  () =>
                  {
                      if (!midiLoaded)
                      {
                          formConsole.AppendText("[ERR] No Midi loaded!" + Environment.NewLine);
                      }
                      else
                      {

                          outputDevice = OutputDevice.GetByName(midiOutput);
                          player = midiFile.GetPlayback(outputDevice);

                          player.NoteCallback = (rawNoteData, rawTime, rawLength, playbackTime) =>
                          {
                              if (IgnoreTracks.Contains(rawNoteData.Channel)) return null;
                              return new NotePlaybackData(
                                  rawNoteData.NoteNumber,   // leave note number as is
                                  rawNoteData.Velocity,     // leave velocity as is
                                  rawNoteData.OffVelocity,  // leave off velocity as is
                                  rawNoteData.Channel);     // leave channel as is

                      };

                          player.Play();

                          player.Finished += playerFinished;
                      }
                  });
                playerThread.IsBackground = true;
                playerThread.Start();
```

**Comment by wolfy01** [comment]
Is the issue caused by starting it in a new thread?

**Comment by melanchall** [comment]
> Is the issue caused by starting it in a new thread?

No, the issue caused by attaching event handler after `Play` method called. From [the docs on `Play`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Devices.Playback.html#Melanchall_DryWetMidi_Devices_Playback_Play):

> Starts playing of the MIDI data. **This method will block execution of a program until all MIDI data is played.**

So that's what happening:

1. you call `Play`
2. execution of the `playerThread` is paused
3. when all MIDI data played, execution goes forward
4. you attach event handler (`player.Finished += playerFinished;`)

But at the moment where you set event handler all MIDI data already played so of course no `Finished` event fired. In fact it's fired, but at the end of `Play` method, when you don't have the event handler attached yet.

Quick fix is just change order of lines to:

```csharp
player.Finished += playerFinished;
player.Play();
```

But I'd suggest you to use another way of playing MIDI data. Please read [Playback - Overview](https://melanchall.github.io/drywetmidi/articles/playback/Overview.html) article on the library docs, section [Non-blocking playback](https://melanchall.github.io/drywetmidi/articles/playback/Overview.html#non-blocking-playback). So you don't need to mess with `playerThread`:

```csharp
if (!midiLoaded)
{
  formConsole.AppendText("[ERR] No Midi loaded!" + Environment.NewLine);
}
else
{

  outputDevice = OutputDevice.GetByName(midiOutput);
  player = midiFile.GetPlayback(outputDevice);

  player.NoteCallback = (rawNoteData, rawTime, rawLength, playbackTime) =>
  {
	  if (IgnoreTracks.Contains(rawNoteData.Channel)) return null;
	  return new NotePlaybackData(
		  rawNoteData.NoteNumber,   // leave note number as is
		  rawNoteData.Velocity,     // leave velocity as is
		  rawNoteData.OffVelocity,  // leave off velocity as is
		  rawNoteData.Channel);     // leave channel as is

  };

  player.Finished += playerFinished;
  player.Start();
}
```

So you call `Start` instead of `Play`. Non-blocking approach allows you to use many features of playback, like time jumps, setting properties while a playback is in progress and so on.

But note, that `player` must be a class field, not a local variable, to prevent garbage collecting of it. `outputDevice` must be a field too. So you create playback in some method and put it to field, and start it somewhere in your program. When you're done with playback, you must dispose it.

**Comment by wolfy01** [comment]
> > Is the issue caused by starting it in a new thread?
> 
> No, the issue caused by attaching event handler after `Play` method called. From [the docs on `Play`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Devices.Playback.html#Melanchall_DryWetMidi_Devices_Playback_Play):
> 
> > Starts playing of the MIDI data. **This method will block execution of a program until all MIDI data is played.**
> 
> So that's what happening:
> 
> 1. you call `Play`
> 2. execution of the `playerThread` is paused
> 3. when all MIDI data played, execution goes forward
> 4. you attach event handler (`player.Finished += playerFinished;`)
> 
> But at the moment where you set event handler all MIDI data already played so of course no `Finished` event fired. In fact it's fired, but at the end of `Play` method, when you don't have the event handler attached yet.
> 
> Quick fix is just change order of lines to:
> 
> ```cs
> player.Finished += playerFinished;
> player.Play();
> ```
> 
> But I'd suggest you to use another way of playing MIDI data. Please read [Playback - Overview](https://melanchall.github.io/drywetmidi/articles/playback/Overview.html) article on the library docs, section [Non-blocking playback](https://melanchall.github.io/drywetmidi/articles/playback/Overview.html#non-blocking-playback). So you don't need to mess with `playerThread`:
> 
> ```cs
> if (!midiLoaded)
> {
>   formConsole.AppendText("[ERR] No Midi loaded!" + Environment.NewLine);
> }
> else
> {
> 
>   outputDevice = OutputDevice.GetByName(midiOutput);
>   player = midiFile.GetPlayback(outputDevice);
> 
>   player.NoteCallback = (rawNoteData, rawTime, rawLength, playbackTime) =>
>   {
> 	  if (IgnoreTracks.Contains(rawNoteData.Channel)) return null;
> 	  return new NotePlaybackData(
> 		  rawNoteData.NoteNumber,   // leave note number as is
> 		  rawNoteData.Velocity,     // leave velocity as is
> 		  rawNoteData.OffVelocity,  // leave off velocity as is
> 		  rawNoteData.Channel);     // leave channel as is
> 
>   };
> 
>   player.Finished += playerFinished;
>   player.Start();
> }
> ```
> 
> So you don't need `playerThread`. You call `Start` instead of `Play`. Non-blocking approach allows you to use many features of playback, like time jumps, setting properties while a playback is in progress and so on.
> 
> But note, that `player` must be a class field, not a local variable, to prevent garbage collecting of it. `outputDevice` must be a field too. So you create playback in some method and put it to field, and start it somewhere in your program. When you're done with playback, you must dispose it.

Thanks
