### ISSUE TITLE
GetTempoMap() won't recognize first tempo change if it's 120 bpm

### ISSUE THREAD

**Issue by juancabrera** [melanchall/drywetmidi#131]
If a midi file has a tempo map, and the first tempo registered is 120bpm `GetTempoMap()` will just skip it. If you change the first tempo to anything but 120bpm it will recognize it.

Attached is a midi that you can reproduce the issue.

[test-tempomap-start-120bpm.mid.zip](https://github.com/melanchall/drywetmidi/files/6704313/test-tempomap-start-120bpm.mid.zip)

**Comment by melanchall** [comment]
Hi,

First of all, let me explain what tempo map is. For example, we have following track chunk with events:

```
   120 120 140 140 140 120 120 130 130
    |   |   |   |   |   |   |   |   |
[...A...B...C...D...E...F...G...H...I...]

 > > time > >
```

where `A`, `B` and so on are _Set Tempo_ events with corresponding BPM (written above the letters). For this sequence of MIDI events tempo map will be:

```
               120 120 140 140 140 120 120 130 130
                |   |   |   |   |   |   |   |   |
events      [...A...B...C...D...E...F...G...H...I...]
                        |           |       |    
                       140         120     130    
                        |           |       |    
tempo map   [           +           +       +       ]
```

where `+` means tempo change point.

So as you can see tempo map doesn't reflect original MIDI events. Tempo map holds **real tempo changes**. Default tempo is 120 BPM by MIDI specifications so there is no need to hold first two tempo "changes" because tempo is not changed in fact. Any repeated values are ignored.

Tempo map is for holding tempo **changes**, not _Set Tempo_ events.

So the behavior you've encountered is absolutely correct. It's how tempo map works.

**Comment by melanchall** [comment]
@juancabrera Do you have any questions or the issue can be closed?

**Comment by juancabrera** [comment]
@melanchall it does makes sense and thank you so much for the detailed explanation!
