### ISSUE TITLE
The last chord is missing

### ISSUE THREAD

**Issue by datacute** [melanchall/drywetmidi#15]
I started writing a program to translate midi files into c source code for a digital music box created by @technoblogy 
http://www.technoblogy.com/show?11TQ

I downloaded the midi file for this tune:
https://musicboxmaniacs.com/explore/melody/scarborough-fair_4694/
The notes collection contains all the notes, but the chords collection is missing the last chord of 4 notes.

**Comment by melanchall** [comment]
Hi Stephen,

Thank you for pointing this out. There was a bug with chords collecting. I fixed it by 12df08beaf9a32a5a86399343d4b6e68bd8e4136 in _develop_ branch. The fix will be in the next release. Or you can take the last version of sources from _develop_ branch and build them to use in your application.

Can you confirm the bug is resolved?

**Comment by datacute** [comment]
Yes, that change fixes what I was seeing.
Thanks!
