### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'Melanchall_DryWetMidi_Native32'

### ISSUE THREAD

**Issue by bib-ak** [melanchall/drywetmidi#164]
My Windows Form application crashes with error message System.DllNotFoundException: Unable to load DLL 'Melanchall_DryWetMidi_Native32'. This does only happen when published - if run from Visual Studio 2017 it works as expected.

Windows 10
.NET 4.6
Visual Studio 2017
Melanchall added from Nuget package (6.0.1)

**Comment by melanchall** [comment]
Hi,

> This does only happen when published

Can you please explain what do you mean? Also please show me content of the folder you "publish" project to?

**Comment by bib-ak** [comment]
It run fine in Visual Studio hitting the "Start" button (Debug or Release). Then I go to Visual Studio "Build" -> "Publish". It generates an install file. When installing my application and run it - it breaks.
[publish.zip](https://github.com/melanchall/drywetmidi/files/8133324/publish.zip)

**Comment by bib-ak** [comment]
A simple code example:
`using System;
using System.Windows.Forms;
using Melanchall.DryWetMidi.Multimedia;
using Melanchall.DryWetMidi.Core;
using Melanchall.DryWetMidi.Interaction;
using Melanchall.DryWetMidi.MusicTheory;
using Melanchall.DryWetMidi.Composing;
using Melanchall.DryWetMidi.Common;

namespace WindowsFormsApplication6
{


    public partial class Form1 : Form
    {

        public Form1()
        {
            InitializeComponent();

        }


        private void Form1_Load(object sender, EventArgs e)
        {

        }
        private void OnEventReceived(object sender, MidiEventReceivedEventArgs e)
        {
            var midiDevice = (MidiDevice)sender;
            Console.WriteLine($"Event received from '{midiDevice.Name}' at {DateTime.Now}: {e.Event}");
        }

        private void OnEventSent(object sender, MidiEventSentEventArgs e)
        {
            var midiDevice = (MidiDevice)sender;
            Console.WriteLine($"Event sent to '{midiDevice.Name}' at {DateTime.Now}: {e.Event}");
        }

        private void panel1_MouseDown(object sender, MouseEventArgs e)
        {
            var patternBuilder = new PatternBuilder()

                .Note(Octave.Get(4).A, new MusicalTimeSpan(5, 17), (SevenBitNumber)68);

            using (var outputDevice = OutputDevice.GetByName("vMIDI"))
            {
                outputDevice.EventSent += OnEventSent;

                using (var inputDevice = InputDevice.GetByName("vMIDI"))
                {
                    inputDevice.EventReceived += OnEventReceived;
                    inputDevice.StartEventsListening();

                    outputDevice.SendEvent(new NoteOnEvent((SevenBitNumber)Int32.Parse(textBox1.Text), (SevenBitNumber)127));
                    outputDevice.SendEvent(new NoteOffEvent());
                }
            }
        }
    }
}`

**Comment by melanchall** [comment]
Well, I have never build installers via Publish. Thanks for the case, let's investigate how to fix the problem.

First of all, I see _Application Files_ folder in your archive. Can you please say, will these files be installed automatically by installer so they will be placed near exe? If so, I suggest to place there all native libraries. You can find them in the _bin_ folder of your application (just hit Build and take a look at the folder). All such files have _Native_ word in their names.

**Comment by melanchall** [comment]
@bib-ak Any news?

**Comment by bib-ak** [comment]
If you install the attached archive you will see where the files are extracted.

I also have tested with adding a "Setup Project" (VS->File->Add) with no success. But: when adding the "Native" dll files to primary output of installed program - it works.

Maybe someone read this and save some time :) Thank you for your work, really appreciated.

**Comment by melanchall** [comment]
I leave the issue open. Maybe I'll be able to fix it on my side.

**Comment by Tony-Pappas** [comment]
I'm having this same issue. I pull the code down fresh, then build solution in Debug. The build fails with

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'InputDevice' does not contain a definition for 'TestCheckpoints' and no accessible extension method 'TestCheckpoints' accepting a first argument of type 'InputDevice' could be found (are you missing a using directive or an assembly reference?)	Melanchall.DryWetMidi.Tests (netcoreapp3.1)	C:\Users\Tony\Downloads\drywetmidi-6.1.0\DryWetMidi.Tests\Multimedia\InputDevice\InputDeviceTests.Common.cs	171	N/A

and

> Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'OutputDevice' does not contain a definition for 'TestCheckpoints' and no accessible extension method 'TestCheckpoints' accepting a first argument of type 'OutputDevice' could be found (are you missing a using directive or an assembly reference?)	Melanchall.DryWetMidi.Tests (netcoreapp3.1)	C:\Users\Tony\Downloads\drywetmidi-6.1.0\DryWetMidi.Tests\Multimedia\OutputDevice\OutputDeviceTests.Common.cs	128	N/A

So, I ignore the build errors (because they are in the Tests project) and try to use Melanchall.DryWetMidi. but I get a runtime error:

> System.DllNotFoundException
  HResult=0x80131524
  Message=Unable to load DLL 'Melanchall_DryWetMidi_Native64' or one of its dependencies: The specified module could not be found. (0x8007007E)
  Source=Melanchall.DryWetMidi
  StackTrace:
   at Melanchall.DryWetMidi.Multimedia.CommonApi64.GetApiType()
   at Melanchall.DryWetMidi.Multimedia.CommonApi64.Api_GetApiType() in A:\Code\Libraries3rdParty\GitHub\drywetmidi\DryWetMidi\Multimedia\Common\CommonApi64.cs:line 27
   at Melanchall.DryWetMidi.Multimedia.MidiDevicesSession.GetSessionHandle() in A:\Code\Libraries3rdParty\GitHub\drywetmidi\DryWetMidi\Multimedia\Session\MidiDevicesSession.cs:line 40
   at Melanchall.DryWetMidi.Multimedia.MidiDevice.EnsureSessionIsCreated() in A:\Code\Libraries3rdParty\GitHub\drywetmidi\DryWetMidi\Multimedia\MidiDevice.cs:line 134
   at Melanchall.DryWetMidi.Multimedia.OutputDevice.GetByName(String name) in A:\Code\Libraries3rdParty\GitHub\drywetmidi\DryWetMidi\Multimedia\OutputDevice\OutputDevice.cs:line 444
   at TrainingApp.MidiPlayer..ctor() in A:\Code\Prosonic\MusicMachineLearning\TrainingApp\MidiPlayback\MidiPlayer.cs:line 27
   at TrainingApp.Program.PlayResult(ITrainerResult result) in A:\Code\Prosonic\MusicMachineLearning\TrainingApp\Program.cs:line 32
   at TrainingApp.Program.<Trainer_IterationCompleted>d__1.MoveNext() in A:\Code\Prosonic\MusicMachineLearning\TrainingApp\Program.cs:line 24

It appears that the project is pointing at three dll files that don't exist:
![image](https://user-images.githubusercontent.com/30202655/170842867-3fd356b8-057c-407b-bda6-8eec51feea11.png)

**Comment by melanchall** [comment]
@Tony-Pappas Regarding `TestCheckpoints` errors see here please: #189

As for missing DLLs, of course, because you just use the code. If you install the library via NuGet package (or Unity asset if you use the library in Unity), all required files will be installed automatically. But if you really need to use raw code, just take native binaries and put them in DryWetMidi folder. Please see at point **3** at [Using in Unity → Manual installation](https://melanchall.github.io/drywetmidi/articles/dev/Using-in-Unity.html#manual-installation) article. You can see there how to get an archive with required DLLs.

**Comment by Tony-Pappas** [comment]
That's just what the doctor ordered!

Your code is elegant (a superb project!) and you're always so quick to reply to issues. 👍

Thank you very much, Maxim!

**Comment by joeduf** [comment]
Did you release the source code for building Melanchall_DryWetMidi_Native32.dll Melanchall_DryWetMidi_Native64.dll and Melanchall_DryWetMidi_Native64.dylib? I can't find it anywhere and would prefer to not blindly use DLLs in binary form.

**Comment by melanchall** [comment]
@joeduf Of course, you can see the code and even build it by yourself if you want. See here please: https://github.com/melanchall/drywetmidi/tree/develop/Resources/Native
