### ISSUE TITLE
InputDevice event listening crash

### ISSUE THREAD

**Issue by mdarveau** [melanchall/drywetmidi#262]
Hi,

First, thanks for the *great* lib. I'm building a Unity app to help practice drum rudiments and this lib has been a HUGE time saver. Thanks for doing such a great job at API design and documentation.

I'm listening for MIDI input with the following code:
```
    void Start() {
        foreach (var input in InputDevice.GetAll()) {
            Debug.Log(input.Name);
        }
        InputDevice inputDevice = InputDevice.GetByName("DTX drums");
        inputDevice.EventReceived += OnMidiEventReceived;
        inputDevice.StartEventsListening();
    }

    private static void OnMidiEventReceived(object sender, MidiEventReceivedEventArgs e)
    {
        var midiDevice = (MidiDevice)sender;
        Debug.Log($"Event received from '{midiDevice.Name}' at {DateTime.Now}: {e.Event}");
    }
```

And I get a bunch of events (mostly Timing Clock and Active Sensing events) and then I get this error and the whole Unity editor freeze.

```
NullReferenceException: Object reference not set to an instance of an object
Melanchall.DryWetMidi.Multimedia.InputDevice.OnMessage_Mac (System.IntPtr pktlist, System.IntPtr readProcRefCon, System.IntPtr srcConnRefCon) (at <1ee5422f8ce74a06831827bb5f773e0a>:0)
(wrapper native-to-managed) Melanchall.DryWetMidi.Multimedia.InputDevice.OnMessage_Mac(intptr,intptr,intptr)
UnityEngine.<>c:<RegisterUECatcher>b__0_0(Object, UnhandledExceptionEventArgs) (at /Users/bokken/build/output/unity/unity/Runtime/Export/Scripting/UnhandledExceptionHandler.bindings.cs:46)
```

Any idea what could be going on?
I'm on mac 13.4 (22F66), DryWetMidi 6.1.4, Unity 2022.2.20f1, and the drum is a Yamaha DTX.

Thanks a lot!

**Comment by melanchall** [comment]
Hi,

I suppose it's because you create **local** variable `inputDevice`. What happens when `Start` method exits? Right, all local variables are marked as ready for garbage collection, so they will be deleted within short time span. So your `OnMidiEventReceived` method is attached to deleted entity when `Start` exited.

Just declare `inputDevice` as a class field, not as a local var. See [Input device](https://melanchall.github.io/drywetmidi/articles/devices/Input-device.html) article to learn more.

Thanks,
Max

**Comment by mdarveau** [comment]
That is exactly it! Thanks so much!!
