### ISSUE TITLE
React to playback events

### ISSUE THREAD

**Issue by ianespana** [melanchall/drywetmidi#33]
So, I was wondering if it's possible to play a MIDI file and not output it to a MIDI device, but instead execute code whenever a MIDI event happens (such as NoteOn).

**Comment by melanchall** [comment]
Hi,

Thanks for your question! At now it's not possible, but I'll add corresponding event to the `Playback` class as soon as possible.

**Comment by melanchall** [comment]
@ianespana , I've added `EventPlayed` event (09b7c45bf2cfdef28117b6278c34f0fa207f6581) to `Playback` class so you can react on every played event even without `OutputDevice` set. You can build the library from sources (**develop** branch) to try the new feature right now.

**Comment by ianespana** [comment]
Perfect! I'll try it out and let you know if I find any issues. Thanks a lot!

**Comment by melanchall** [comment]
Sounds good :) Waiting for your response.

**Comment by ianespana** [comment]
So, it works. But now I'm facing two new issues.
The first one is that, if you change the playback's output device from nothing to something, start and stop the playback and then try to start it again, it just poops itself and throws a `The specified device is already in use.  Wait until it is free, and then try again` error.

The second thing I'd like to as is if it's possible to get the MIDI's tick so I can implement a scroll bar to my program which moves forward as the song progresses

**Comment by melanchall** [comment]
You can take current time in MIDI ticks via `GetCurrentTime<MidiTimeSpan>()` method of the `Playback` class.

**Comment by ianespana** [comment]
I think I expressed wrong. I want an even to trigger on every tick of the MIDI clock so I can keep the scroll bar synced to the music, and also so I can avoid making another timer if one is already running

**Comment by melanchall** [comment]
Internal MIDI clock of playback run with interval of 1 ms. With such small timer interval it's recommended to avoid some additional logic which can lead to playback latency. My suggestion right now is to create separate timer with interval of 10 ms for example and poll current time of playback.

But I'll think on adding some event that will be fired with the specified interval. For example, if you set interval to 100 ms, the event will be fired when playback position is advanced by 100 ms.

Thank you. I really appreciate that you share your experience and ask questions!

**Comment by melanchall** [comment]
I'm going to create special class for this purpose which will run another high-resolution timer and watch current time of the specified playbacks.

**Comment by ianespana** [comment]
Right. One more thing, is it possible to get the note information for inputdevices?

**Comment by melanchall** [comment]
> is it possible to get the note information for inputdevices?

What do you mean? Receive note events via input device?

**Comment by ianespana** [comment]
Yep, but figured it out. You can get the input event and cast it to `NoteOnEvent`, which has all the information I needed (and can't believe I didn't figure this out earlier...)

**Comment by melanchall** [comment]
Yes, that's how it should be done :)

---

I've added `PlaybackCurrentTimeWatcher` class to watch current position of playback(s). This class is singleton in order to prevent too many high resolution timers are created (which is not good since it can affect whole system performance).

Small example:

```csharp
PlaybackCurrentTimeWatcher.Instance.AddPlayback(playback, TimeSpanType.Midi);
PlaybackCurrentTimeWatcher.Instance.CurrentTimeChanged += OnCurrentTimeChanged;
PlaybackCurrentTimeWatcher.Instance.Start();

// ...

private static void OnCurrentTimeChanged(object sender, PlaybackCurrentTimeChangedEventArgs e)
{
    foreach (var playbackTime in e.Times)
    {
        var playback = playbackTime.Playback;
        var time = (MidiTimeSpan)playbackTime.Time;

        Console.WriteLine($"Current time is {time}.");
    }
}
```

In this example we watch current time of playback and request to report time in `Midi` format which is ticks (and thus we cast received time to `MidiTimeSpan`). You can set any desired time format and cast to corresponding implementation of the `ITimeSpan`.

You can add multiple different playbacks to watch their current times. When you don't want to watch playback anymore remove it from the watcher:

```csharp
PlaybackCurrentTimeWatcher.Instance.RemovePlayback(playback);
```

By default polling interval of watcher is 100 ms, but you can alter it:

```csharp
PlaybackCurrentTimeWatcher.Instance.PollingInterval = TimeSpan.FromMilliseconds(50);
```

Please don't set too small intervals. I recommend to use the default value or something greater than 10 ms. Polling interval defines how often `CurrentTimeChanged` event will be fired. If you want to pause firing the event, call `Stop` method.

When your application is about to close, please dispose watcher to kill the internal timer:

```csharp
PlaybackCurrentTimeWatcher.Instance.Dispose();
```

Thank you for making the library better! Waiting for your feedback on playback time watching.

**Comment by melanchall** [comment]
@ianespana Did you try playback watcher?

**Comment by melanchall** [comment]
@ianespana Please give me your feedback so we can proceed to either closing the issue or redesigning API.

**Comment by ianespana** [comment]
Sorry @melanchall , I've been very busy and haven't been able to try it yet. I will update my local version of the library today and give it a try. Thanks

**Comment by ianespana** [comment]
Works very well. Thanks a lot!

**Comment by melanchall** [comment]
Thank you for using the library! Feel free to open new issues or ask questions :)
