### ISSUE TITLE
Midi recording without input device?

### ISSUE THREAD

**Issue by Yorgg** [melanchall/drywetmidi#54]
I would like to send midi events to the midi `Recording` without using the `InputDevice`.   

Perhaps If we change `OnEventReceived` to be public then other objects could subscribe to it?  
Something like this: 

`customEventGenerator.ProcessMidiEvent += recording.OnEventReceived`

And the InputDevice could be optional in the `Recording` class? 

https://github.com/melanchall/drywetmidi/blob/ce71820e4679bf605b2f726aed4068347e36caa4/DryWetMidi/Devices/Recording/Recording.cs

**Comment by Yorgg** [comment]
It seems like if we make the `OnEventReceived` method public, it would work? 

```
/// Recording.cs

private void OnEventReceived(object sender, MidiEventReceivedEventArgs e)
        {
            if (!IsRunning)
                return;

            _events.Add(new RecordingEvent(e.Event, _stopwatch.Elapsed));
        }
```

**Comment by melanchall** [comment]
Hi,

I think it will be better to introduce interface like `IInputDevice` that will be implemented by standard `InputDevice` and that you can implement by yourself. `IInputDevice` will contain event `EventReceived`. And `Recording` will work with that interface rather than with `InputDevice`.

In my opinion it's more flexible way. Please tell me if it sounds good.

**Comment by Yorgg** [comment]
Agreed. That sounds good.

**Comment by melanchall** [comment]
I've added `IInputDevice` interface:

```csharp
public interface IInputDevice
{
    event EventHandler<MidiEventReceivedEventArgs> EventReceived;

    bool IsListeningForEvents { get; }

    void StartEventsListening();

    void StopEventsListening();
}
```
