### ISSUE TITLE
Ability to send raw MIDI messages

### ISSUE THREAD

**Issue by windlight2** [melanchall/drywetmidi#55]
Is there any way to send raw MIDI messages using SendEvent() in the form of a byte[] and bypass the object wrappers? Because sometimes the user needs to be able to send a non-predetermined or ambiguous MIDI command, including ones not defined in the standard MIDI spec.

For example the managed-midi library allows you to do this as such:
`outputDevice.Send(new byte [] {0x90, 0x40, 0x70}, 0, 3, 0);`

I was hoping that drywetmidi has an equivalent function. Thanks!

**Comment by melanchall** [comment]
Hi,

Nice feature request! At now you cannot send events as bytes, but I'll definitely add this ability.

Please note that you cannot send absolutely arbitrary bytes. In MIDI standard there are two types of MIDI events you can send/receive: channel and system exclusive.

System exclusive events already can be sent as bytes:

```csharp
outputDevice.SendEvent(new NormalSysExEvent(new byte[] { ... }));
```

So I suppose you're talking about sending **channel events** (line _Note On_ or _Program Change_) as bytes, right?

**Comment by windlight2** [comment]
Yes, we love using undefined MIDI commands for gaming-related applications. I personally like using control change or sysex messages that are not picked up by MIDI players to ensure backwards compatibility. Although I know others who use NoteOn events too.

**Comment by melanchall** [comment]
So why did you close the issue? :)
I'll implement sending channel events as bytes within the issue since sysex messages can be sent as bytes right now.

**Comment by windlight2** [comment]
Thank you!

**Comment by melanchall** [comment]
I decided to keep current signature of `SendEvent`. **BUT** it's obviously useful to have ability to get events from bytes. So I've added two classes:
* `BytesToMidiEventConverter` which takes bytes array and returns `MidiEvent` read from the bytes;
* `MidiEventToBytesConverter` which takes `MidiEvent` and returns byte array representing the event.

Both classes implement `IDisposable` so don't forget to use these classes inside `using` block or call `Dispose` manually.

So you can use `BytesToMidiEventConverter` to get `MidiEvent` and then pass that event to `SendEvent` method of `OutputDevice`.

Although it looks a bit complicated, in my opinion this way is much more flexible since it's basic. New classes can be used for different scenarios, not for MIDI events sending only, providing the same API.

New classes are in **develop** branch so if you want to use them right now, please build the library from sources.

**Comment by MusicalMiqo** [comment]
Excellent

**Comment by melanchall** [comment]
Please give your feedback (suggestions, questions, ...) or close the issue.

**Comment by MusicalMiqo** [comment]
I can't close the issue anymore.

**Comment by clarkx86** [comment]
Hey!
First of all thank you for this wonderful library and secondly sorry for bumping this closed issue.

However I was wondering the same as @windlight2 and stumbled upon this thread. Do you have any estimated plan when this feature will be merged into master?

Thank you and have a great day,
clarkx86 :-)

**Comment by melanchall** [comment]
@clarkx86, I received notification about your comment but unfortunately I don't see it on GitHub :( You're interested in when I'll release new version of the library including changes regarding this issue. I can't say exact date but I'll try to make release in the beginning of February.
