### ISSUE TITLE
CsvConverter#ConvertMidiFileToCsv closes stream

### ISSUE THREAD

**Issue by saviourofdp** [melanchall/drywetmidi#73]
The CsvConverter method

```cs
public void ConvertMidiFileToCsv(MidiFile midiFile, Stream stream, MidiFileCsvConversionSettings settings = null);
```
automatically closes the stream. Would it be possible to add an option that prevents this? I find I need to convert to CSV in order to compare midifiles but I don't want to have to write to disk. Unless there's a better way of comparing `MidiFile`s?
```cs
midiFile1.Equals(midiFile2)
``` 
doesn't seem to work.

**Comment by melanchall** [comment]
Hi,

It's a bug that `CsvConverter` closes stream. I've fixed this in develop branch.

Also converting to CSV is not a good way to compare MIDI files. I'll try to provide comparing API.

**Comment by melanchall** [comment]
I've added following static methods:

```csharp
MidiFile.Equals(MidiFile midiFile1, MidiFile midiFile2)
MidiFile.Equals(MidiFile midiFile1, MidiFile midiFile2, out string message)
MidiFile.Equals(MidiFile midiFile1, MidiFile midiFile2, MidiFileEqualityCheckSettings settings, out string message)
```

Since `MidiFile` is a pretty complex object, overloads with `message` are very useful since `message` will contain info about what is different in MIDI files.

New API is in _develop_ branch so if you want to try it right now, you need to download sources and build library by yourself.

**Comment by melanchall** [comment]
@saviourofdp Any news on this issue?

**Comment by melanchall** [comment]
I'm closing the issue. Bug is fixed, equality check API is added.
