### ISSUE TITLE
Play Midi with an „internal“ driver..

### ISSUE THREAD

**Issue by FischertBilligheim** [melanchall/drywetmidi#83]
Hi Max,

How can I do a playback without a midi-device? This sounds stupid - yes, but:

The idea is to use the „fluidsynth“-dll and and the c#-wrapper of it (Nfluidsynth) as an „internal“ player for mididata by using a soundfount.

The „Nfluidsynth“ project has a simple interface for note_on/note_off/Set_controllers etc. I would do these calls in the Midi-Event Callback. But for that I need a Midi-device, correct?

Best regards
Thomas

**Comment by melanchall** [comment]
Hi Thomas,

You have two options:

1. **Use `Playback` without output device.**  
  You can play MIDI data with `Playback` class without output device. There are `Playback` constructors that don't have `outputDevice` parameter. Also all `GetPlayback` extension methods (for example [`GetPlayback(midiFile, clockSettings = null)`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Devices.PlaybackUtilities.html#Melanchall_DryWetMidi_Devices_PlaybackUtilities_GetPlayback_Melanchall_DryWetMidi_Core_MidiFile_Melanchall_DryWetMidi_Devices_MidiClockSettings_)) have overloads without this parameter. More than that you can set [`Playback.OutputDevice`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Devices.Playback.html#Melanchall_DryWetMidi_Devices_Playback_OutputDevice) property to `null` at any time. So you can play MIDI data without MIDI device and get all callbacks called.
2. **Create custom output device**  
  In fact, playback API works with [`IOutputDevice`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Devices.IOutputDevice.html) interface rather than with `OutputDevice` class. Last one is built-in inplementation of `IOutputDevice`. So you can create your own implementation and use it as output device for playback. In your case I suppose you can implement just [`SendEvent`](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Devices.IOutputDevice.html#Melanchall_DryWetMidi_Devices_IOutputDevice_SendEvent_Melanchall_DryWetMidi_Core_MidiEvent_) method and leave other ones empty.

In my opinion, the last option is preferred. I believe all I/O operations should be incapsulated in devices and not in general events or callbacks. Also it will be easier to reuse I/O code.

**Comment by FischertBilligheim** [comment]
Hi Max,

Thanks again a lot for your great support!
I will proceed with the „Custom output device“-approach.

Best regards
Thomas
