### ISSUE TITLE
Inaccurate TimeSignature.AtTime() with MIDI files containing multiple time signature changes

### ISSUE THREAD

**Issue by atalkingfish** [melanchall/drywetmidi#92]
I'm using DryWetMidi on Unity, and I noticed that if I try to get the TimeSignature at a given microsecond, it does one of the two following things:

(1) If the microsecond is 0, it returns the very first time signature in the MIDI file.

(2) If the microsecond is greater than 0, it returns the very last time signature in the MIDI file.

Example: if I make a MIDI file with the time signature changing every 2 measures—4/4, 3/6, 7/4, 5/4, 13/16—and check the time signature on every beat (using BarBeatTicksTimeSpan(i, 0)), it returns the following: 4/4, 13/16, 13/16, 13/16, 13/16, 13/16, 13/16, 13/16, 13/16, 13/16,

Here is the code I am using:

```
var nextBeatMicroseconds = TimeConverter.ConvertTo<MetricTimeSpan>(new BarBeatTicksTimeSpan(i, 0), tempoMap)
                .TotalMicroseconds;
var nextBeatTimeSignature = tempoMap.TimeSignature.AtTime(nextBeatMicroseconds);
```

I increments until the MIDI file is complete.

This is currently presenting major issues for a project I am almost complete with, however it has only come to my attention now because I have not had any MIDI files change time signature up to this point. Is this a bug, or an issue with my implementation? I have confirmed that the "nextBeatMicroseconds" returns the various appropriate times throughout the project (they do not just return the beginning or very end of the project).

**Comment by melanchall** [comment]
Hi,

You have bug in your code here:

```csharp
var nextBeatTimeSignature = tempoMap.TimeSignature.AtTime(nextBeatMicroseconds);
```

`AtTime(long time)` accepts `time` in terms of MIDI ticks, not microseconds, so you get those strange results. But thank you for pointing out that my [documentation on this method](https://melanchall.github.io/drywetmidi/api/Melanchall.DryWetMidi.Interaction.ValueLine-1.html#Melanchall_DryWetMidi_Interaction_ValueLine_1_AtTime_System_Int64_) doesn't say that `time` is in MIDI ticks. I'll fix it.

Please try this:

```csharp
var nextBarTicks = TimeConverter.ConvertFrom(new BarBeatTicksTimeSpan(i, 0), tempoMap);
var nextBarTimeSignature = tempoMap.TimeSignature.AtTime(nextBarTicks);
```

Also I've replace `beat` with `bar` because you iterate over starts of bars not beats (`i` stands on `bars` parameter position).

**Comment by atalkingfish** [comment]
MIDI ticks... that’s very helpful. I can see the complete oversight of mine in assuming that microseconds was going to work. I’ve been using microseconds for my project (because it’s needful to read the notes by metric time). Complete oversight on my part. Thanks a ton for so clearly and quickly pointing that out to me, and updating the documentation. Really good stuff!

**Comment by atalkingfish** [comment]
The proposed solution worked as intended. Thank you!

**Comment by melanchall** [comment]
Hmm, I think it would be better to have methods on `TempoMap` directly, like

```csharp
tempoMap.GetTimeSignatureAtTime(...)
```

where we can request time signature with any time span representation, like

```csharp
var nextBarTimeSignature = tempoMap.GetTimeSignatureAtTime(new BarBeatTicksTimeSpan(i, 0));
```

It reduces number of calls which are redundant since tempo map already knows about itself and we have no need to use time conversions.

Thank you again!

**Comment by atalkingfish** [comment]
Are you suggesting that I do this, or are you considering adding the functions? I ask because "GetTimeSignatureAtTime" isn't a class available to me on tempoMap.

It's worth noting I did consolidate it into one line...
`var nextBarTimeSignature = tempoMap.TimeSignature.AtTime(TimeConverter.ConvertTo<MidiTimeSpan>(new BarBeatTicksTimeSpan(i, 0), tempoMap));`

but not in a way that reduces the total number of calls because the conversion is still there.

**Comment by melanchall** [comment]
I'm just thinking about adding new features to the library. By myself of course :) I've put it to my backlog. It will be much simpler than current approach and will remove ambiguity (as with `long` in your case).
